//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atinformstudy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATinformContainer : DbContext
    {
        public ATinformContainer()
            : base("name=ATinformContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> CourseSet { get; set; }
        public virtual DbSet<Group> GroupSet { get; set; }
        public virtual DbSet<GroupStudent> GroupStudentSet { get; set; }
        public virtual DbSet<Content> ContentSet { get; set; }
        public virtual DbSet<Attachment> AttachmentSet { get; set; }
        public virtual DbSet<AtUser> AtUserSet { get; set; }
        public virtual DbSet<Comment> CommentSet { get; set; }
    }
}
